name: Manual Labels Sync

on:
  workflow_dispatch:
    inputs:
          logLevel:
            description: 'Log level'
            required: true
            default: 'warning'
            type: choice
            options:
            - info
            - warning
            - debug
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: micnncim/action-label-syncer@v1
        with:
          manifest: https://github.com/Eiwa-ai/.github/blob/main/labels.yml
          repository: |
              https://github.com/Eiwa-ai/.github/
              https://github.com/Eiwa-ai/.github-private/
          token: ${{ secrets.PERSONAL_TOKEN }}
