name: Sync Labels

on:
  push:
    paths:
      - '.github/labels.yml'
  workflow_dispatch:

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub PyYAML

      - name: Sync labels
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_PAT }}
          ORG_NAME: ${{ secrets.ORG_NAME }}
        run: |
          python - <<EOF
          import os
          import yaml
          from github import Github

          def load_labels_from_yaml(file_path):
              with open(file_path, 'r') as file:
                  return yaml.safe_load(file)

          def sync_labels(repo, labels_config):
              existing_labels = {label.name.lower(): label for label in repo.get_labels()}
              
              for label in labels_config:
                  name = label['name']
                  color = label['color']
                  description = label.get('description', '')
                  
                  if name.lower() in existing_labels:
                      existing_label = existing_labels[name.lower()]
                      if existing_label.color != color or existing_label.description != description:
                          existing_label.edit(name, color, description)
                      del existing_labels[name.lower()]
                  else:
                      repo.create_label(name, color, description)
              
              # Remove old labels that don't match the config
              for label in existing_labels.values():
                  label.delete()

          g = Github(os.environ['GITHUB_TOKEN'])
          org = g.get_organization(os.environ['ORG_NAME'])
          labels_config = load_labels_from_yaml('.github/labels.yml')

          for repo in org.get_repos():
              print(f"Syncing labels for {repo.name}")
              sync_labels(repo, labels_config)

          print("Label sync completed.")
          EOF
