name: Sync Labels

on:
  push:
    paths:
      - '.github/labels.yml'
  workflow_dispatch:

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch organization repositories
        id: fetch-repos
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.ORG_PAT }}
          script: |
            const org = 'Eiwa-ai';
            const repos = await github.paginate(github.rest.repos.listForOrg, {
              org: org,
              type: 'all'
            });
            return repos.map(repo => repo.name);

      - name: Sync labels
        uses: micnncim/action-label-syncer@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_PAT }}
        with:
          manifest: .github/labels.yml
          repository: |
            ${{ steps.fetch-repos.outputs.result }}
          prune: true
