name: Sync Labels Across Organization

on:
  push:
    branches:
      - main  # or master, depending on your default branch name
    paths:
      - '.github/labels.yml'
  workflow_dispatch:  # Allow manual triggering

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get list of organization repositories
        id: org-repos
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.ORG_PAT }}
          script: |
            const org = context.repo.owner;
            const repos = await github.paginate(github.rest.repos.listForOrg, {
              org: org,
              type: 'all'
            });
            return repos.map(repo => repo.name);

      - name: Sync labels for each repository
        uses: micnncim/action-label-syncer@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_PAT }}
        with:
          manifest: .github/labels.yml
          repository: ${{ github.repository }}
          prune: true

      - name: Sync labels across all repositories
        uses: actions/github-script@v6
        env:
          REPOS: ${{ steps.org-repos.outputs.result }}
        with:
          github-token: ${{ secrets.ORG_PAT }}
          script: |
            const fs = require('fs');
            const yaml = require('js-yaml');
            
            const labelsYml = fs.readFileSync('.github/labels.yml', 'utf8');
            const labels = yaml.load(labelsYml);
            
            const re
